### ISSUE TITLE
Project Fails To Load Under PHP 7.0.22

### ISSUE THREAD

**Issue by Spotlightsrule** [Gipetto/CowSay#1]
Hello. I deployed this project to my website and installed the dependencies via composer, but I got these following errors when including the Calf.php file
Warning: include(): Failed opening 'cowsay/src/tests/vendor/demo.php' for inclusion (include_path='.:/usr/shar/php') in/var/www/html/assets/template/dependencies.php on line 3
Fatal error: Uncaught Error: Class 'Cow' not found in /var/www/html/pages/about/index.php:23 Stack trace: #0 {main} thrown in /var/www/html/pages/about/index.php on line 23

Not sure if this is only occurring in my own environment, so I submitted here in case it's not exclusive. I can also include error logs if you need them to diagnose the issue.

**Comment by Gipetto** [comment]
Can you tell me how you installed cowsay? And also show how you're trying to use it in your page?

**Comment by Gipetto** [comment]
A purely basic use would be:
```php
<?php                                                                              
                                                                                   
require_once 'vendor/autoload.php';                                                
                                                                                   
use CowSay\Cow;                                                                    
                                                                                   
$bessie = new Cow('Hello, Farm!');                                                 
echo $bessie;
```

**Comment by Spotlightsrule** [comment]
I downloaded the repository to my web server, navigated to the root project folder, and executed the command for composer. I am planning to use the output in the error pages along with a fortune generator that I'll create to go with it. I am calling the project via a master dependencies file that is 1 directory up from the project folder.

**Comment by Spotlightsrule** [comment]
Ok. thanks for the help. It's working just fine now.
